/**
 * Mock Data for Development
 * Test data to preview UI components without connecting to FiveM
 */

import type { PlayerInventory, ItemDefinition, PlayerEquipment, EquipmentSlot } from '@/types';

export const mockItemDefinitions: Record<string, ItemDefinition> = {
  ak47: {
    name: 'ak47',
    label: 'AK-47',
    description: '7.62x39mm assault rifle',
    type: 'weapon',
    category: 'weapon',
    image: '/assets/items/weapon_smg.png',
    size: { width: 4, height: 2 },
    rotatable: true,
    stackable: false,
    weight: 3.5,
    base_value: 15000,
    usable: false,
    consumable: false,
    weapon_type: 'rifle',
    caliber: '7.62x39',
    damage: 45,
    equipSlot: 'primary',
    metadata_template: {
      durability: 100,
      max_durability: 100,
    },
  },
  m4a1: {
    name: 'm4a1',
    label: 'M4A1',
    description: '5.56x45mm assault rifle',
    type: 'weapon',
    category: 'weapon',
    image: '/assets/items/weapon_smg.png',
    size: { width: 4, height: 2 },
    rotatable: true,
    stackable: false,
    weight: 3.2,
    base_value: 18000,
    usable: false,
    consumable: false,
    weapon_type: 'rifle',
    caliber: '5.56x45',
    equipSlot: 'primary',
    metadata_template: {
      durability: 100,
      max_durability: 100,
    },
  },
  glock17: {
    name: 'glock17',
    label: 'Glock 17',
    description: '9mm pistol',
    type: 'weapon',
    category: 'weapon',
    image: '/assets/items/weapon_pistol.png',
    size: { width: 2, height: 2 },
    rotatable: true,
    stackable: false,
    weight: 0.8,
    base_value: 5000,
    usable: false,
    consumable: false,
    weapon_type: 'pistol',
    caliber: '9x19',
    equipSlot: 'holster',
    metadata_template: {
      durability: 100,
      max_durability: 100,
    },
  },
  bandage: {
    name: 'bandage',
    label: 'Bandage',
    description: 'Stops bleeding',
    type: 'medical',
    category: 'medical',
    image: '/assets/items/bandage.png',
    size: { width: 1, height: 1 },
    rotatable: false,
    stackable: true,
    max_stack: 10,
    weight: 0.05,
    base_value: 50,
    usable: true,
    consumable: true,
    stops_bleeding: true,
  },
  medkit: {
    name: 'medkit',
    label: 'Medical Kit',
    description: 'Restores 50 HP (multiple uses)',
    type: 'medical',
    category: 'medical',
    image: '/assets/items/medkit.png',
    size: { width: 2, height: 2 },
    rotatable: false,
    stackable: false,
    weight: 0.5,
    base_value: 500,
    usable: true,
    consumable: false,
    heal_amount: 50,
    metadata_template: {
      durability: 3,
      max_durability: 3,
    },
  },
  water_bottle: {
    name: 'water_bottle',
    label: 'Water',
    description: 'Restores hydration (can drink progressively)',
    type: 'consumable',
    category: 'food',
    image: '/assets/items/water.png',
    size: { width: 1, height: 2 },
    rotatable: true,
    stackable: false,
    weight: 0.5,
    base_value: 20,
    usable: true,
    consumable: true,
    hydration: 50,
    metadata_template: {
      durability: 100, // Water bottle has durability (can drink partially)
      max_durability: 100,
    },
  },
  mre: {
    name: 'mre',
    label: 'MRE',
    description: 'Military food ration',
    type: 'consumable',
    category: 'food',
    image: '/assets/items/burger.png',
    size: { width: 2, height: 1 },
    rotatable: true,
    stackable: false,
    weight: 0.3,
    base_value: 100,
    usable: true,
    consumable: true,
    energy: 100,
  },
  helmet_lvl3: {
    name: 'helmet_lvl3',
    label: 'Level 3 Helmet',
    description: 'Heavy combat helmet',
    type: 'helmet',
    category: 'helmet',
    image: '/assets/items/hat.png',
    size: { width: 2, height: 2 },
    rotatable: false,
    stackable: false,
    weight: 1.5,
    base_value: 8000,
    usable: false,
    consumable: false,
    armor_class: 3,
    armor_zones: ['head'],
    armor_durability: 100,
    equipSlot: 'headgear',
    metadata_template: {
      durability: 100,
      max_durability: 100,
    },
  },
  armor_lvl4: {
    name: 'armor_lvl4',
    label: 'Level 4 Armor',
    description: 'Heavy body armor',
    type: 'armor',
    category: 'armor',
    image: '/assets/items/vest.png',
    size: { width: 3, height: 3 },
    rotatable: false,
    stackable: false,
    weight: 8.0,
    base_value: 25000,
    usable: false,
    consumable: false,
    armor_class: 4,
    armor_zones: ['thorax', 'stomach'],
    armor_durability: 100,
    equipSlot: 'armor',
    metadata_template: {
      durability: 100,
      max_durability: 100,
    },
  },
  backpack_large: {
    name: 'backpack_large',
    label: 'Military',
    description: 'Military tactical backpack',
    type: 'backpack',
    category: 'backpack',
    image: '/assets/items/backpack.png',
    size: { width: 4, height: 4 },
    rotatable: false,
    stackable: false,
    weight: 2.0,
    base_value: 5000,
    usable: false,
    consumable: false,
    container_grid: { width: 8, height: 10 },
    equipSlot: 'backpack',
  },
  backpack_sentry: {
    name: 'backpack_sentry',
    label: 'Sentry 305',
    description: 'Sentry 305 tactical backpack',
    type: 'backpack',
    category: 'backpack',
    image: '/assets/items/backpack.png',
    size: { width: 4, height: 5 },
    rotatable: false,
    stackable: false,
    weight: 2.5,
    base_value: 8000,
    usable: false,
    consumable: false,
    container_grid: { width: 9, height: 11 },
    equipSlot: 'backpack',
  },
  backpack_raider: {
    name: 'backpack_raider',
    label: 'Raider',
    description: 'Raider assault backpack',
    type: 'backpack',
    category: 'backpack',
    image: '/assets/items/backpack.png',
    size: { width: 4, height: 4 },
    rotatable: false,
    stackable: false,
    weight: 1.8,
    base_value: 4500,
    usable: false,
    consumable: false,
    container_grid: { width: 7, height: 9 },
    equipSlot: 'backpack',
  },
  backpack_bergen: {
    name: 'backpack_bergen',
    label: 'Bergen',
    description: 'Bergen military rucksack',
    type: 'backpack',
    category: 'backpack',
    image: '/assets/items/backpack.png',
    size: { width: 5, height: 5 },
    rotatable: false,
    stackable: false,
    weight: 3.0,
    base_value: 12000,
    usable: false,
    consumable: false,
    container_grid: { width: 10, height: 12 },
    equipSlot: 'backpack',
  },
  ammo_762: {
    name: 'ammo_762',
    label: '7.62x39 Ammo',
    description: 'Box of 30 rounds',
    type: 'ammo',
    category: 'ammo',
    image: '/assets/items/762x39_fmj.png',
    size: { width: 1, height: 1 },
    rotatable: false,
    stackable: true,
    max_stack: 10,
    weight: 0.3,
    base_value: 100,
    usable: false,
    consumable: false,
    ammo_caliber: '7.62x39',
  },
  secure_case: {
    name: 'secure_case',
    label: 'Secure Case',
    description: 'Permanent secure container',
    type: 'container',
    category: 'container',
    image: '/assets/items/secure_case.png',
    size: { width: 2, height: 2 },
    rotatable: false,
    stackable: false,
    weight: 0.5,
    base_value: 0,
    usable: false,
    consumable: false,
    container_grid: { width: 3, height: 1 },
    equipSlot: 'case',
  },
  card: {
    name: 'card',
    label: 'Map Card',
    description: 'Military tactical map (permanent)',
    type: 'map',
    category: 'misc',
    image: '/assets/items/map.png',
    size: { width: 2, height: 1 },
    rotatable: false,
    stackable: false,
    weight: 0.1,
    base_value: 0,
    usable: true,
    consumable: false,
  },
  compass: {
    name: 'compass',
    label: 'Compass',
    description: 'Navigation compass (permanent)',
    type: 'tool',
    category: 'misc',
    image: '/assets/items/compass.png',
    size: { width: 1, height: 1 },
    rotatable: false,
    stackable: false,
    weight: 0.1,
    base_value: 0,
    usable: true,
    consumable: false,
  },
  minimap: {
    name: 'minimap',
    label: 'Mini-Map Device',
    description: 'Tactical map display (permanent)',
    type: 'map',
    category: 'misc',
    image: '/assets/items/card.png',
    size: { width: 2, height: 1 },
    rotatable: false,
    stackable: false,
    weight: 0.1,
    base_value: 0,
    usable: true,
    consumable: false,
  },
  knife: {
    name: 'knife',
    label: 'Knife',
    description: 'Standard issue combat knife (permanent)',
    type: 'melee',
    category: 'weapon',
    image: '/assets/items/weapon_knife.png',
    size: { width: 1, height: 2 },
    rotatable: true,
    stackable: false,
    weight: 0.3,
    base_value: 0,
    usable: true,
    consumable: false,
    equipSlot: 'sheath',
  },
  tactical_rig: {
    name: 'tactical_rig',
    label: 'Tactical Rig',
    description: 'Military chest rig with storage',
    type: 'rig',
    category: 'rig',
    image: '/assets/items/rig_tactical.png',
    size: { width: 3, height: 2 },
    rotatable: false,
    stackable: false,
    weight: 1.2,
    base_value: 8000,
    usable: false,
    consumable: false,
    container_grid: { width: 6, height: 3 },
    equipSlot: 'rig',
    fillsBodyArmor: false,
  },
  plate_carrier: {
    name: 'plate_carrier',
    label: 'Plate Carrier',
    description: 'Armored plate carrier with integrated body armor and storage',
    type: 'rig',
    category: 'rig',
    image: '/assets/items/vest.png',
    size: { width: 3, height: 3 },
    rotatable: false,
    stackable: false,
    weight: 8.5,
    base_value: 35000,
    usable: false,
    consumable: false,
    container_grid: { width: 4, height: 2 },
    equipSlot: 'rig',
    fillsBodyArmor: true, // This rig also provides body armor protection
    armor_class: 4,
    armor_zones: ['thorax', 'stomach'],
    armor_durability: 100,
    armor_material: 'ceramic',
  },
  // Surgical Kits (with durability - multiple uses)
  surgical_kit_basic: {
    name: 'surgical_kit_basic',
    label: 'Basic Surgical Kit',
    description: 'Basic medical supplies for treating injuries',
    type: 'medical',
    category: 'medical',
    image: '/assets/items/medkit.png',
    size: { width: 2, height: 1 },
    rotatable: true,
    stackable: false,
    weight: 0.3,
    base_value: 500,
    usable: true,
    consumable: false,
    heal_amount: 30,
    stops_bleeding: true,
    cures_fracture: false,
    metadata_template: {
      durability: 1,
      max_durability: 1,
    },
  },
  surgical_kit_advanced: {
    name: 'surgical_kit_advanced',
    label: 'Advanced Surgical Kit',
    description: 'Advanced medical supplies for complex injuries',
    type: 'medical',
    category: 'medical',
    image: '/assets/items/medkit.png',
    size: { width: 2, height: 2 },
    rotatable: false,
    stackable: false,
    weight: 0.6,
    base_value: 1500,
    usable: true,
    consumable: false,
    heal_amount: 50,
    stops_bleeding: true,
    cures_fracture: true,
    metadata_template: {
      durability: 2,
      max_durability: 2,
    },
  },
  surgical_kit_military: {
    name: 'surgical_kit_military',
    label: 'Military Surgical Kit',
    description: 'Military-grade medical supplies',
    type: 'medical',
    category: 'medical',
    image: '/assets/items/medkit.png',
    size: { width: 2, height: 2 },
    rotatable: false,
    stackable: false,
    weight: 0.8,
    base_value: 3500,
    usable: true,
    consumable: false,
    heal_amount: 75,
    stops_bleeding: true,
    cures_fracture: true,
    metadata_template: {
      durability: 4,
      max_durability: 4,
    },
  },
  surgical_kit_elite: {
    name: 'surgical_kit_elite',
    label: 'Elite Surgical Kit',
    description: 'Top-tier medical supplies for field surgery',
    type: 'medical',
    category: 'medical',
    image: '/assets/items/medkit.png',
    size: { width: 3, height: 2 },
    rotatable: true,
    stackable: false,
    weight: 1.2,
    base_value: 8000,
    usable: true,
    consumable: false,
    heal_amount: 100,
    stops_bleeding: true,
    cures_fracture: true,
    metadata_template: {
      durability: 8,
      max_durability: 8,
    },
  },
  // Health Syringes (with durability - stored charges)
  health_syringe_basic: {
    name: 'health_syringe_basic',
    label: 'Health Syringe',
    description: 'Basic health restoration syringe',
    type: 'medical',
    category: 'medical',
    image: '/assets/items/bandage.png',
    size: { width: 1, height: 1 },
    rotatable: false,
    stackable: false,
    weight: 0.1,
    base_value: 300,
    usable: true,
    consumable: false,
    heal_amount: 40,
    heal_over_time: true,
    heal_duration: 5,
    metadata_template: {
      durability: 120,
      max_durability: 120,
    },
  },
  health_syringe_advanced: {
    name: 'health_syringe_advanced',
    label: 'Advanced Health Syringe',
    description: 'Advanced health restoration syringe',
    type: 'medical',
    category: 'medical',
    image: '/assets/items/bandage.png',
    size: { width: 1, height: 1 },
    rotatable: false,
    stackable: false,
    weight: 0.15,
    base_value: 1000,
    usable: true,
    consumable: false,
    heal_amount: 60,
    heal_over_time: true,
    heal_duration: 5,
    metadata_template: {
      durability: 400,
      max_durability: 400,
    },
  },
  health_syringe_military: {
    name: 'health_syringe_military',
    label: 'Military Health Syringe',
    description: 'Military-grade health restoration syringe',
    type: 'medical',
    category: 'medical',
    image: '/assets/items/bandage.png',
    size: { width: 1, height: 2 },
    rotatable: true,
    stackable: false,
    weight: 0.2,
    base_value: 2500,
    usable: true,
    consumable: false,
    heal_amount: 100,
    heal_over_time: true,
    heal_duration: 5,
    metadata_template: {
      durability: 960,
      max_durability: 960,
    },
  },
  // Canned Drinks (no durability - instant consumption)
  energy_drink_can: {
    name: 'energy_drink_can',
    label: 'Energy Drink',
    description: 'Canned energy drink (instant)',
    type: 'consumable',
    category: 'food',
    image: '/assets/items/water.png',
    size: { width: 1, height: 1 },
    rotatable: false,
    stackable: true,
    max_stack: 5,
    weight: 0.2,
    base_value: 50,
    usable: true,
    consumable: true,
    hydration: 30,
    energy: 20,
  },
  soda_can: {
    name: 'soda_can',
    label: 'Soda Can',
    description: 'Canned soda (instant)',
    type: 'consumable',
    category: 'food',
    image: '/assets/items/water.png',
    size: { width: 1, height: 1 },
    rotatable: false,
    stackable: true,
    max_stack: 5,
    weight: 0.2,
    base_value: 25,
    usable: true,
    consumable: true,
    hydration: 25,
  },
  // Juice Bottles (with durability - can drink progressively)
  juice_bottle: {
    name: 'juice_bottle',
    label: 'Juice Bottle',
    description: 'Fruit juice bottle (can drink progressively)',
    type: 'consumable',
    category: 'food',
    image: '/assets/items/water.png',
    size: { width: 1, height: 2 },
    rotatable: true,
    stackable: false,
    weight: 0.5,
    base_value: 40,
    usable: true,
    consumable: true,
    hydration: 60,
    energy: 10,
    metadata_template: {
      durability: 100,
      max_durability: 100,
    },
  },
};

export const mockInventory: PlayerInventory = {
  backpack_storage: {
    item_id: 'backpack_large',
    width: 5,
    height: 10,
    items: [
      {
        id: 'item_1',
        item_id: 'ak47',
        quantity: 1,
        position: { x: 0, y: 0 },
        rotation: 0,
        slot_type: 'grid',
        metadata: {
          durability: 85,
          max_durability: 100,
          loaded_magazine: 'ak_mag_30',
        },
      },
      {
        id: 'item_2',
        item_id: 'medkit',
        quantity: 1,
        position: { x: 0, y: 2 },
        rotation: 0,
        slot_type: 'grid',
        metadata: {
          durability: 3,
          max_durability: 3,
        },
      },
      {
        id: 'item_3',
        item_id: 'water_bottle',
        quantity: 1,
        position: { x: 2, y: 2 },
        rotation: 0,
        slot_type: 'grid',
        metadata: {
          durability: 75, // 75% full
          max_durability: 100,
        },
      },
      {
        id: 'item_4',
        item_id: 'mre',
        quantity: 1,
        position: { x: 0, y: 4 },
        rotation: 0,
        slot_type: 'grid',
      },
      {
        id: 'item_5',
        item_id: 'ammo_762',
        quantity: 5,
        position: { x: 0, y: 9 },
        rotation: 0,
        slot_type: 'grid',
      },
    ],
  },
  case_storage: {
    width: 3,
    height: 1,
    items: [
      {
        id: 'case_card',
        item_id: 'card',
        quantity: 1,
        position: { x: 0, y: 0 },
        rotation: 0,
        slot_type: 'case_storage',
      },
      {
        id: 'case_compass',
        item_id: 'compass',
        quantity: 1,
        position: { x: 2, y: 0 },
        rotation: 0,
        slot_type: 'case_storage',
      },
    ],
  },
  backpack: {
    width: 8,
    height: 10,
    items: [],
  },
  rig: {
    item_id: 'tactical_rig',
    width: 4,
    height: 3,
    items: [
      {
        id: 'rig_1',
        item_id: 'bandage',
        quantity: 4,
        position: { x: 0, y: 0 },
        rotation: 0,
        slot_type: 'rig',
      },
      {
        id: 'rig_2',
        item_id: 'ammo_762',
        quantity: 3,
        position: { x: 1, y: 0 },
        rotation: 0,
        slot_type: 'rig',
      },
      {
        id: 'rig_3',
        item_id: 'water_bottle',
        quantity: 1,
        position: { x: 3, y: 0 },
        rotation: 0,
        slot_type: 'rig',
        metadata: {
          durability: 100,
          max_durability: 100,
        },
      },
    ],
  },
  pockets: [
    {
      index: 0,
      item: {
        id: 'pocket_1',
        item_id: 'bandage',
        quantity: 3,
        rotation: 0,
        slot_type: 'pocket',
        slot_index: 0,
      },
    },
    { index: 1, item: null },
    { index: 2, item: null },
    { index: 3, item: null },
    { index: 4, item: null },
  ],
  equipment: [
    {
      slot_name: 'headgear',
      item: {
        id: 'equip_head',
        item_id: 'helmet_lvl3',
        quantity: 1,
        rotation: 0,
        slot_type: 'equipment',
        metadata: { durability: 95, max_durability: 100 },
      },
    },
    { slot_name: 'headset', item: null },
    { slot_name: 'face_cover', item: null },
    {
      slot_name: 'armor',
      item: {
        id: 'equip_armor',
        item_id: 'armor_lvl4',
        quantity: 1,
        rotation: 0,
        slot_type: 'equipment',
        metadata: { durability: 100, max_durability: 100 },
      },
    },
    {
      slot_name: 'rig',
      item: {
        id: 'equip_rig',
        item_id: 'tactical_rig',
        quantity: 1,
        rotation: 0,
        slot_type: 'equipment',
      },
    },
    {
      slot_name: 'backpack',
      item: {
        id: 'equip_backpack',
        item_id: 'backpack_large',
        quantity: 1,
        rotation: 0,
        slot_type: 'equipment',
      },
    },
    {
      slot_name: 'holster',
      item: {
        id: 'equip_holster',
        item_id: 'glock17',
        quantity: 1,
        rotation: 0,
        slot_type: 'equipment',
        metadata: { durability: 100, max_durability: 100, loaded_magazine: 'glock_mag_17' },
      },
    },
    {
      slot_name: 'sheath',
      item: {
        id: 'equip_sheath',
        item_id: 'knife',
        quantity: 1,
        rotation: 0,
        slot_type: 'equipment',
      },
    },
    {
      slot_name: 'case',
      item: {
        id: 'equip_case',
        item_id: 'secure_case',
        quantity: 1,
        rotation: 0,
        slot_type: 'equipment',
      },
    },
    {
      slot_name: 'primary',
      item: {
        id: 'equip_primary',
        item_id: 'm4a1',
        quantity: 1,
        rotation: 0,
        slot_type: 'equipment',
        metadata: { durability: 92, max_durability: 100 },
      },
    },
    { slot_name: 'secondary', item: null },
  ],
  current_weight: 22.5,
  max_weight: 50.0,
};

export function createMockEquipment(): PlayerEquipment {
  const slots: EquipmentSlot[] = mockInventory.equipment;

  return {
    headgear: slots.find(s => s.slot_name === 'headgear')?.item || null,
    headset: slots.find(s => s.slot_name === 'headset')?.item || null,
    face_cover: slots.find(s => s.slot_name === 'face_cover')?.item || null,
    armor: slots.find(s => s.slot_name === 'armor')?.item || null,
    rig: slots.find(s => s.slot_name === 'rig')?.item || null,
    backpack: slots.find(s => s.slot_name === 'backpack')?.item || null,
    holster: slots.find(s => s.slot_name === 'holster')?.item || null,
    sheath: slots.find(s => s.slot_name === 'sheath')?.item || null,
    case: slots.find(s => s.slot_name === 'case')?.item || null, // ⭐ NEW: Permanent secure case
    primary: slots.find(s => s.slot_name === 'primary')?.item || null,
    secondary: slots.find(s => s.slot_name === 'secondary')?.item || null,
  };
}
